### PR TITLE
Fix ChangeNotifierProvider builder argument

### LINKED ISSUE #442: Using builder in ChangeNotifierProvider's constructor throws an exception
```Dart
@override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Goods List Page')),
      body: ChangeNotifierProvider(
        create: (_) => GoodsListModel(),
        builder: _buildGoodsListView,
      ),
    );
  }

  Widget _buildGoodsListView(BuildContext context, _) {
    final model = Provider.of<GoodsListModel>(context, listen: false);
    return ListView.builder(
      itemCount: model.goodList.length,
      itemBuilder: (context, index) => Builder(builder: (context) => _buildGoodsItem(context, index)),
    );
  }
```

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building ChangeNotifierProvider<GoodsListModel>(dirty, message: 'package:provider/src/inherited_provider.dart': Failed assertion: line 126 pos 12: 'child != null': ChangeNotifierProvider<GoodsListModel> used outside of MultiProvider must specify a child\nSee also: https://flutter.dev/docs/testing/errors, dirty, renderObject: RenderErrorBox#ee35f NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE):
ChangeNotifierProvider<GoodsListModel> used outside of MultiProvider must specify a child
'package:provider/src/inherited_provider.dart':
Failed assertion: line 126 pos 12: 'child != null'

The relevant error-causing widget was: 
  ChangeNotifierProvider<GoodsListModel> file:///Users/wangzhiming26/Desktop/jd-projects/%E6%B1%AA%E5%B8%88%E5%82%85/flutter_engineer_wang/example/lib/main.dart:90:13
When the exception was thrown, this was the stack: 
#2      InheritedProvider.buildWithChild (package:provider/src/inherited_provider.dart:126:12)
#3      SingleChildStatelessWidget.build (package:nested/nested.dart:260:41)
#4      StatelessElement.build (package:flutter/src/widgets/framework.dart:4576:28)
#5      SingleChildStatelessElement.build (package:nested/nested.dart:280:18)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4502:15)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

### PR DESCRIPTION
**Pull request by passsy**
Fixes a regression which forces users of `ChangeNotifierProvider` to provide a `child` even if a `builder` is provided.

```dart
// AssertionError: ChangeNotifierProvider<GoodsListModel> used outside of MultiProvider must specify a child
ChangeNotifierProvider(
  create: (_) => GoodsListModel(),
  builder: _buildGoodsListView,
),
```

Fixes #442

### CODE REVIEW

**Comment by davidmartos96** [comment]
Wouldn't `assert(child != null || builder != null, ...)` work the same way? Maybe that avoids the changes to the `endsWith` tests.

File: lib/src/inherited_provider.dart [hunk 1]
```diff
@@ -123,8 +123,13 @@ class InheritedProvider<T> extends SingleChildStatelessWidget {
...
   Widget buildWithChild(BuildContext context, Widget child) {
-    assert(child != null,
-        '$runtimeType used outside of MultiProvider must specify a child');
+    assert(() {
+      if (_builder == null && child == null) {
+        throw AssertionError(
+            '$runtimeType used outside of MultiProvider must specify a child');
+      }
+      return true;
+    }());
```
Comment (passsy) [inline lib/src/inherited_provider.dart:132]: Might be just be, but this is easier to understand than

```dart
assert(_builder != null || child != null, 
    '$runtimeType used outside of MultiProvider must specify a child');
```

Comment (rrousselGit) [reply lib/src/inherited_provider.dart:132]: Why not:

```dart
assert(_builder == null && child == null,
        '$runtimeType used outside of MultiProvider must specify a child');
```

?

File: test/inherited_provider_test.dart [hunk 2]
```diff
@@ -459,7 +459,7 @@ The context used was: Context
       isA<AssertionError>().having(
         (source) => source.toString(),
         'toString',
-        endsWith(
+        contains(
```
Comment (rrousselGit) [inline test/inherited_provider_test.dart:462]: Why is this needed?

**Comment by rrousselGit** [comment]
Thanks!
